name: Daily Random Commits

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:

jobs:
  random-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Maybe Commit
        run: |
          git config --global user.email "vaibhavkesarwani100@gmail.com"
          git config --global user.name "Vaibhav"

          # Random number of commits this run: 0, 1, or 2
          COMMITS=$(1 + (RANDOM % 3))
          echo "This run will make $COMMITS commits."

          for i in $(seq 1 $COMMITS); do
            bun run dev
            echo "Commit $i at $(date)" >> commit-log.txt

            git add README.md commit-log.txt || true
            git commit -m "Random commit $i on $(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M')"
            git push origin main
          done
